# .github/workflows/main.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install NPM dependencies
        run: npm -g install

      - name: Update NPM
        run: npm update

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://nelson-serverless/soapyballs/prod/.serverless .serverless --delete

      - name: Serverless AWS authentication
        run: npx serverless --component=serverless-next config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: Deploy Next.js app
        run: npx serverless

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless ss3://nelson-serverless/soapyballs/prod/.serverless --delete
